### PR TITLE
Ashvat

### PR DESCRIPTION
**Pull request by Asr161**
Worked on the AccountManager usecase that is the base of the entire program. It is responsible for adding and removing users, adding and removing friends. Used a hashmap to store the users i.e. a mapping from the username to the user (object). The Graph and the User are the 2 entities, the latter representing the users and the former a collection of the users. The user class has several getter and setter methods, so does the graph class. The FriendAdder, FriendRemover, UserCreator usecases were implemented in accordance with the SOLID principle of single responsibility. The databases package contains the readgraph and writegraph classes that are responsible for storing the graph into a file and reading from it when required from the code. Lat few commits include changes to the loginpage and welcome page in the UI to accommodate changes that ensures the successful storing of the graph to the file.

### CODE REVIEW

**Comment by Jangalang2911** [comment]
In order to set up the tests for my use-cases, I had to review with the AccountManager, and the Graph and User entities. The straightforward organization of the Graph, alongside the Network manipulation methods (FriendAdder, FriendRemover etc), made it very easy to get familiarized and make a mock network of users. As opposed to the earlier implementation an abstract Vertex class and a User subclass, having only the User subclass makes it easier to access User objects and manipulate their points, while reducing the number of superfluous dependencies. Overall, clean and efficient code, a new user would have no major problem understanding and utilizing the packages.

**Review by egemertakin — APPROVED** [review]
I have reviewed your code for account manager and adding friends, removing friends etc. Your methods in account manager were separated in an organized way and it followed the solid principles and clean architecture. I was able to connect your account manager methods to the welcome page and login page. Great job.

**Review by ArianKhademi — APPROVED** [review]
Looked it over. All looks great. Good job!

**Review by Jangalang2911 — DISMISSED** [review]
In order to set up the tests for my use-cases, I had to review with the AccountManager, and the Graph and User entities. The straightforward organization of the Graph, alongside the Network manipulation methods (FriendAdder, FriendRemover etc), made it very easy to get familiarized and make a mock network of users. As opposed to the earlier implementation an abstract Vertex class and a User subclass, having only the User subclass makes it easier to access User objects and manipulate their points, while reducing the number of superfluous dependencies. Overall, clean and efficient code, a new user would have no major problem understanding and utilizing the packages.

**Pull request merged**
