### PR TITLE
Mertakin

### PR DESCRIPTION
**Pull request by egemertakin**
Completed all of the components of the Tic-Tac-Toe game. The way it works is UI has 9 buttons, 1 for each grid on the board. After every move the GameUI class calls the controller and the moves on the board are converted to an Arraylist so the usecase (GameManager) can check whether there is a winning move after every move, if there is, the controller gets that information and the winner is shown on the UI. After one of the users win, the points of that user is increased. This happens when the controller calls the pointssystem usecase. Therefore, the program for the game follows Clean Architecture and Solid principles completely. For GameUI to work the GameUI object should be called with two parameters which are the two User object who will be playing against each other.

### CODE REVIEW

**Review by Manit2210 — DISMISSED** [review]
Your implementation of the game seems good to me. Creating a move tracker is a reasonable approach to have taken. The tests also seem to take edge cases into consideration and the UI built with java swing looks well-structured as well. I have noticed the use of clean architecture throughout your code as well as the GameUI. LGTM!

**Review by Manit2210 — DISMISSED** [review]
Your implementation of the game seems good to me. Creating a move tracker is a reasonable approach to have taken. The tests also seem to take edge cases into consideration and the UI built with java swing looks well-structured as well. I have noticed the use of clean architecture throughout your code as well as the GameUI. The chat connected to the welcome page is also a good touch. Code follows clean architecture and looks good to me.

**Review by ArianKhademi — DISMISSED** [review]
I have reviewed the code for the GameUI, GameController, GameManager, and MoveTracker files, as well as the test files MoveTrackerTests and GameManagerTests. All of the files appear to have good use of java documentation which allow it to be easy to understand what each method and each class is used for. Through the classes used to create and manage the game I notice that the code appears to follow clean architecture principles and correctly and achieves the desired result every time. The points for the users appear to correctly be updated based on the result of the tic-tac-toe game and the GUI looks very nice for the game too. Through the video you had shown me, as well as the test files I can see where every result/possibility from the tic-tac-toe game is correctly accounted for and tested, and that the game functions perfectly well. In addition to the game files the GUI for the pages and the connections between the pages all appear to be done well and everything seems to be connecting and running smoothly. Nice job!

**Review by BYT18 — APPROVED** [review]
Your implementation of the game follows SOLID principles as well as clean architecture through the clear use of controllers and use cases. This correctly and effectively connects the various use cases to the UI and its features. UI is also well done and looks simple and clean. The code is functional and easy to follow along due to the clear documentation. I checked the tests and the confirm that the game and UI are communicating the correct info and working properly. Nice work.

**Review by Manit2210 — APPROVED** [review]
Your implementation of the game seems good to me. Creating a move tracker is a reasonable approach to have taken. The tests also seem to take edge cases into consideration and the UI built with java swing looks well-structured as well. I have noticed the use of clean architecture throughout your code as well as the GameUI. The chat connected to the welcome page is also a good touch. Code follows clean architecture and looks good to me.

**Review by BYT18 — APPROVED** [review]
Your implementation of the game follows SOLID principles as well as clean architecture through the clear use of controllers and use cases. This correctly and effectively connects the various use cases to the UI and its features. UI is also well done and looks simple and clean. The code is functional and easy to follow along due to the clear documentation. I checked the tests and the confirm that the game and UI are communicating the correct info and working properly. Nice work.

**Review by ArianKhademi — APPROVED** [review]
I have reviewed the code for the GameUI, GameController, GameManager, and MoveTracker files, as well as the test files MoveTrackerTests and GameManagerTests. All of the files appear to have good use of java documentation which allow it to be easy to understand what each method and each class is used for. Through the classes used to create and manage the game I notice that the code appears to follow clean architecture principles and correctly and achieves the desired result every time. The points for the users appear to correctly be updated based on the result of the tic-tac-toe game and the GUI looks very nice for the game too. Through the video you had shown me, as well as the test files I can see where every result/possibility from the tic-tac-toe game is correctly accounted for and tested, and that the game functions perfectly well. In addition to the game files the GUI for the pages and the connections between the pages all appear to be done well and everything seems to be connecting and running smoothly. Nice job!

**Pull request merged**
