### PR TITLE
Brandon friend management system

### PR DESCRIPTION
**Pull request by BYT18**
Implemented the friend management system that includes classes like FriendAdder that allows users to add friends and also adds edges to the corresponding user vertices. FriendRemover allows users to remove friends and also removes the corresponding edges between users. FriendRecommendation system parses through the current users neighbors / friends to find the most common shared friend amongst them and returns to current user as the best recommendation. These use cases are followed by controllers such as AddUIController which connect the UI with respective use cases and sends them the correct parameters. Finally, pull includes some UI and tests for the important algorithms and use cases.

### CODE REVIEW

**Comment by Manit2210** [comment]
The friend recommender function is implemented well and the logic seems to be on point after my review. The iteration through friends' friends is a correct approach. There is a valid check to not include the current user when checking friends' friends so no chance of that edge case causing an error. The testing for the methods in this class passed and the test also seems appropriate and inclusive of edge cases. The friend remover method also looks good to me as both the user and friends list of friends are edited. The account manager class has implemented called method appropriately as well. All tests look good to me.

**Review by Manit2210 — DISMISSED** [review]
The friend recommender function is implemented well and the logic seems to be on point after my review. The iteration through friends' friends is a correct approach. There is a valid check to not include the current user when checking friends' friends so no chance of that edge case causing an error. The testing for the methods in this class passed and the test also seems appropriate and inclusive of edge cases. The friend remover method also looks good to me as both the user and friends list of friends are edited. The account manager class has implemented called method appropriately as well. All tests look good to me.

**Comment by Asr161** [comment]
efficient implementation of the getRecommendation function which passes all the tests. Covered all the edge cases to ensure the appropriate working of the function. The tests ensure that all the edge cases have been checked. The list of friends is being edited after the implementation of this function, thereby accomplishing the goal.

**Review by Asr161 — APPROVED** [review]
efficient implementation of the getRecommendation function which passes all the tests. Covered all the edge cases to ensure the appropriate working of the function. The tests ensure that all the edge cases have been checked. The list of friends is being edited after the implementation of this function, thereby accomplishing the goal.

**Review by Manit2210 — APPROVED** [review]
The friend recommender function is implemented well and the logic seems to be on point after my review. The iteration through friends' friends is a correct approach. There is a valid check to not include the current user when checking friends' friends so no chance of that edge case causing an error. The testing for the methods in this class passed and the test also seems appropriate and inclusive of edge cases. The friend remover method also looks good to me as both the user and friends list of friends are edited. The account manager class has implemented called method appropriately as well. All tests look good to me. There is clear use of clean architecture and SOLID Principle. The addition of FriendAdder and FriendRemover with the use AccountManager is an example of this clean architecture you implmented. Good job!

**Review by ArianKhademi — APPROVED** [review]
I have reviewed your FriendRecommender class as well as your methods, and I believe everything is good to go. Your getRecommend method seems to efficiently and effectively accomplish searching the graph and correctly recommending the friend which has the most mutual friends. Likewise, your getRecommendRandom method also appears to have been implemented correctly. The FriendRecommenderTest file appears to accurately test everything required, and everything passes as expected. Your test file has been very carefully planned and you can see that all edge cases have been accounted for and all cases are correctly tested as well, which helps definitively demonstrate that your classes and methods work well. Additionally, your code throughout your classes and methods is very clean and well documented. Well done!

**Pull request merged**
